### ISSUE TITLE
raztot does not work properly when Janus Gateway isn't started

### ISSUE THREAD

**Issue by ewegene** [benbusby/raztot#5]
When starting raztot it has the following prompt:

```
Run Janus Gateway? (y/n)
```

When choosing `n` it will still run and allow you to log in, but video streams don't work.

**Comment by benbusby** [comment]
Not necessarily a bug, since the web app relies on Janus to receive the video stream. The comment in the run script explains that you can skip running Janus if you’re just wanting to test the other aspects of the web app (websocket controls, nginx conf, etc) work without waiting for Janus to start up. 

I’m fine with removing that if it’d be less confusing though. Thoughts?

**Comment by ewegene** [comment]
I don't think it would be necessary to remove it, maybe just a warning indicating that it's required, or perhaps make it a flag rather than a prompt.

**Comment by benbusby** [comment]
Addressed in b1ec349822a53b4036e7b300399ad75632aebb3b 

(added --skip-janus flag, janus runs by default now)
