### ISSUE TITLE
Setup script issues

### ISSUE THREAD

**Issue by geek-at** [benbusby/raztot#8]
Hello again! Here are a few things I found:

- In `setup.sh` under "Generate self-signed certificates" you generate certificates and try to copy them to the /etc/nginx/ path **before** installing nginx (so this will fail)
- You seem to install a large amount of unneeded packages. Over 200 packages including the x-server for some reason
- In the `nginx` part of the `setup.sh` you copy the nginx config to **sites-available** but never link this file to sites-enabled which means the file will never be used. You could install it directly to **sites-enabled** which is not best pactice but gets the job done for this project
- The nginx config includes the link to the certificate files but it will never use them because you specified that the server will only listen on port 80 so all https requests will result in "connection refused" errors. adding "listen 443 ssl;" will fix that

**Comment by benbusby** [comment]
Thanks for the pointers! I unfortunately wrote the setup script from memory, so I'm not surprised you're finding problems there. I should have written the script while I built the project, not afterwards.

- The first is an easy fix, will address soon.
- With the exception of libffi-dev and few others, all of the packages come directly from the recommended packages for Janus, rpicamsrc, all third party resources that were used in the project. I don't really want to take any out at the moment because investigating which are needed and which aren't at the moment isn't really a top priority. If you already know which ones to remove, it'd be more helpful to issue a PR removing them.
- Regarding the third, that's not necessarily true. The nginx config replaces the default config in sites-available, which by default is already linked to sites-enabled when nginx is installed.
- The fourth is also a small fix, so I'll fix this soon.

Again, thank you for the help in pointing these out!

**Comment by benbusby** [comment]
The first and fourth have been fixed now, and since the third pointer isn't an issue I'm going to close this. Feel free to reopen if you disagree. I also created #9 to address your second pointer, but that will probably be lower priority for the time being.

**Comment by lizard626** [comment]
Additional issue: When the setup.sh script gets to the Flask section, it fails with Error: Could not locate Flask application. You did not provide the FLASK_APP environment variable.

**Comment by benbusby** [comment]
@lizard626 that seems weird. FLASK_APP should never even need to be set for installing anything, it's only used for running the application (which the setup script doesn't do). I just did a fresh install/setup not too long ago and didn't encounter this either. 

I created #13 to look into it though -- creating a new issue is preferred over commenting on old/closed ones btw. Feel free to continue the discussion over there!
